common:
    lid_topic:  "/hesai/pandar"
    imu_topic:  "/mti3dk/imu"
    radar_topic : "/radar_pcl2" 
    topic_twist : "/eagle_data/twist"
    topic_inlier_pc2 : "/eagle_data/inlier_pc2"
    topic_outlier_pc2 : "/eagle_data/outlier_pc2"

threshold:
    power_threshold: 0
    distance_near_thresh : 2
    distance_far_thresh : 100
    z_low_thresh : -1
    z_high_thresh : 100
    downsample_method : "VOXELGRID"   #VOXELGRID or APPROX_VOXELGRID or NONE
    downsample_resolution : 0.1
    outlier_removal_method : "RADIUS" #"STATISTICAL" or "RADIUS" or "NONE"
    statistical_mean_k : 30
    statistical_stddev : 1.2
    radius_radius : 0.5
    radius_min_neighbors : 1

cov :
    LASER_POINT_COV : 0.0005
    VELOCITY_COV : 0.5
    GRAVITY_COV : 0.002
    
    
preprocess:
    lidar_type: 1          
    radar_type : 1
    n_scans: 32
    timestamp_unit: 0       # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    feature_enabled: 0
    point_filter_num: 4
    blind: 4

mapping:
    # loss_threshold: 1000
    max_iteration: 4
    cube_side_length: 1000.0
    filter_size_surf: 0.5           
    filter_size_map: 0.5           
    acc_noise: 0.1
    gyr_noise: 0.1
    acc_bias_noise: 0.0001
    gyr_bias_noise: 0.0001
    fov_degree: 180
    det_range: 150.0
    extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic
    extrinsic_t_il: [-0.012713, -0.001295,  0.184497] 
    extrinsic_R_il: [ -0.099438, -0.992995, -0.063813,  
                      0.994106, -0.101923,  0.036942, 
                     -0.043187, -0.059763,  0.997278 ]

    extrinsic_T_ri : [ 0.99299597,  0.10192327,  0.05976348, -0.06827023,
                    -0.09943785,  0.99410623, -0.04318726,  0.00799113,
                    -0.06381254,  0.03694178,  0.99727782, -0.06975817,
                     0.        ,  0.        ,  0.        ,  1.        ]
    extrinsic_T_rl : [ 0.   , -1.   ,  0.   , -0.07 ,
                       1.   ,  0.   ,  0.   ,  0.   ,
                       0.   ,  0.   ,  1.   ,  0.115,
                       0.   ,  0.   ,  0.   ,  1.   ]


pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
    traj_save_path: /home/vdcl/Downloads/PCD